// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTjAZ2-9DHX_LNyGsHVE-HdjT4fp9V5BM',
    appId: '1:840354251710:web:eb7c38eaa288e98d8f6fef',
    messagingSenderId: '840354251710',
    projectId: 'eye-optical-9bdaa',
    authDomain: 'eye-optical-9bdaa.firebaseapp.com',
    storageBucket: 'eye-optical-9bdaa.appspot.com',
    measurementId: 'G-E9G7GRTVQY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSm-eAQE979_tdTnTAWgY7XSlXtKdtiqU',
    appId: '1:840354251710:android:7a1177958fed76838f6fef',
    messagingSenderId: '840354251710',
    projectId: 'eye-optical-9bdaa',
    storageBucket: 'eye-optical-9bdaa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAao3XSSe7MPC1RuTw2VKJ0YjRbKHHSlL0',
    appId: '1:840354251710:ios:cf3d3ff839cea7238f6fef',
    messagingSenderId: '840354251710',
    projectId: 'eye-optical-9bdaa',
    storageBucket: 'eye-optical-9bdaa.appspot.com',
    iosBundleId: 'com.example.eyeopticApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAao3XSSe7MPC1RuTw2VKJ0YjRbKHHSlL0',
    appId: '1:840354251710:ios:471c1bb98abf236a8f6fef',
    messagingSenderId: '840354251710',
    projectId: 'eye-optical-9bdaa',
    storageBucket: 'eye-optical-9bdaa.appspot.com',
    iosBundleId: 'com.example.eyeopticApp.RunnerTests',
  );
}
